# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
##############################################
# General Configuration
##############################################
export PATH=/usr/local/go/bin:$PATH
export GOPATH=/home/vagrant/go
